{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.17.7-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.17.7-dust.jar",
          "url": "cloche-0.17.7-dust.jar",
          "size": 1072435,
          "sha512": "a21c33e642628cfebb00901460962d5b65e402ff1a551142aff039a1fa8cdba1273d2b6bd38b3fb534920ece89ba6987d00bde43ddcc32fd34b4bb32e4a40978",
          "sha256": "92c988519b8be6c34b3f45fe7e1d7cc3e1bd27179a95ea51bb1a84275b58bcca",
          "sha1": "2d65aa04925d7978c3cab6f60f6e1ead3de6ae64",
          "md5": "92a5ac78052c1d99443560a9fdc62d13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.6"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.7.4-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.6.11-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.0-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.8-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.12-dust"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.17.7-dust.jar",
          "url": "cloche-0.17.7-dust.jar",
          "size": 1072435,
          "sha512": "a21c33e642628cfebb00901460962d5b65e402ff1a551142aff039a1fa8cdba1273d2b6bd38b3fb534920ece89ba6987d00bde43ddcc32fd34b4bb32e4a40978",
          "sha256": "92c988519b8be6c34b3f45fe7e1d7cc3e1bd27179a95ea51bb1a84275b58bcca",
          "sha1": "2d65aa04925d7978c3cab6f60f6e1ead3de6ae64",
          "md5": "92a5ac78052c1d99443560a9fdc62d13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.17.7-dust-javadoc.jar",
          "url": "cloche-0.17.7-dust-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.17.7-dust-sources.jar",
          "url": "cloche-0.17.7-dust-sources.jar",
          "size": 81945,
          "sha512": "816c8240ad003d0b7bf2e1a26eff3ec604ee4780858a03ab0a54887e526626413747d42601ae216cd1ef3bd51cf0684073a6f13fd62de860bd23e65bae63f45d",
          "sha256": "c9bc627fa1577333b29639d9f7f9d685fb59d3b89bb25fcc3c4f141e1bed8607",
          "sha1": "346eec3f06d7e31a91e6c755fa58972ac488b2a3",
          "md5": "36e76ee90413f26f5f5d51bb366d631b"
        }
      ]
    }
  ]
}
