{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.7.2-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.2-dust.jar",
          "url": "minecraft-codev-forge-0.7.2-dust.jar",
          "size": 274146,
          "sha512": "d135a5cf856ab2323033fd008fc302979b0389f82284a3b9779dfc2c99aa680c65fc92c226ddff7f1d42346973d94072b6d2e412e358036687aaa0df0a635edd",
          "sha256": "187ab43069d3f9921b1ac01484c602f6d00a34f4713a5bc9269bd77ad127fe6d",
          "sha1": "8a424c4e441c5c76a9f56d16a941ab302de94399",
          "md5": "a8bbba6be766e03caf79b6053b355f31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.0-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.8-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.2-dust.jar",
          "url": "minecraft-codev-forge-0.7.2-dust.jar",
          "size": 274146,
          "sha512": "d135a5cf856ab2323033fd008fc302979b0389f82284a3b9779dfc2c99aa680c65fc92c226ddff7f1d42346973d94072b6d2e412e358036687aaa0df0a635edd",
          "sha256": "187ab43069d3f9921b1ac01484c602f6d00a34f4713a5bc9269bd77ad127fe6d",
          "sha1": "8a424c4e441c5c76a9f56d16a941ab302de94399",
          "md5": "a8bbba6be766e03caf79b6053b355f31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.2-dust-sources.jar",
          "url": "minecraft-codev-forge-0.7.2-dust-sources.jar",
          "size": 34820,
          "sha512": "98622e22e641485206b28c2f418f912cc612d5508ae6d8cf27a411bc2305be05de1b82a42db03de3b50a35395934aaf478d7aef598fb32c4f705b2e5ba34b4a5",
          "sha256": "e785eed86de8a2de81920e870043eef75d07a6b8b292cd60b246975c4a7bbe57",
          "sha1": "7c2b671224cb7a170cd4b35074161d46475cfa6d",
          "md5": "05accddfe4b6c8a61f2b8a0d812fd030"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.2-dust-javadoc.jar",
          "url": "minecraft-codev-forge-0.7.2-dust-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
