{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-fabric",
    "version": "0.6.11-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-fabric-0.6.11-dust.0.jar",
          "url": "minecraft-codev-fabric-0.6.11-dust.0.jar",
          "size": 134898,
          "sha512": "a26598a0456bbc7ced0aaef610e5d27b7e947b4873b357cae702f993a9877703a0c0f31bf257fd4387286a2c50ef19565dae8930fc8459bfc20bd3ce434d5f2a",
          "sha256": "fbe6748f87f6ce70ec6d354d96789b2d47622c045d0e54e4a769c0a18b3f2f76",
          "sha1": "5cf063397ee047fb95780602307615201d093046",
          "md5": "3f5784a61f032ff5ab071dcd61aa8c05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.0-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.8-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.7"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-fabric-0.6.11-dust.0.jar",
          "url": "minecraft-codev-fabric-0.6.11-dust.0.jar",
          "size": 134898,
          "sha512": "a26598a0456bbc7ced0aaef610e5d27b7e947b4873b357cae702f993a9877703a0c0f31bf257fd4387286a2c50ef19565dae8930fc8459bfc20bd3ce434d5f2a",
          "sha256": "fbe6748f87f6ce70ec6d354d96789b2d47622c045d0e54e4a769c0a18b3f2f76",
          "sha1": "5cf063397ee047fb95780602307615201d093046",
          "md5": "3f5784a61f032ff5ab071dcd61aa8c05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-fabric-0.6.11-dust.0-sources.jar",
          "url": "minecraft-codev-fabric-0.6.11-dust.0-sources.jar",
          "size": 17154,
          "sha512": "6b06925f4d071b3699c398de38f0419c83920e6d21e6aaba1c1722c6b2ee42d4330f3fd8d87d2190c3007ef75c6756b8163caa74c78801ce9c4883c5c605effa",
          "sha256": "4fb626b8862bd2c9392fe11070d1c2fc338a580bfef8772893f3683ec5d93580",
          "sha1": "6f5c8d9bee83833d5c2196aa7d77b796af8ec777",
          "md5": "c8e71c5081fea36801ef001426abb28d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-fabric-0.6.11-dust.0-javadoc.jar",
          "url": "minecraft-codev-fabric-0.6.11-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
