{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-access-widener",
    "version": "0.6.0-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust.jar",
          "size": 75726,
          "sha512": "41b68a28f66199031ecda3f5c73f310d8c7f2f0fdc59205411468cc1bf5553d6834b342280ce509f319e1a0d004f1be2ddad10d68ea405a8203b858235648d75",
          "sha256": "0b322e56ea6db56d110db79e3edee4c80849fbe05dec8733ed41f3970726c76c",
          "sha1": "d227641c659ba6f5f0d02270344483bc4b80adde",
          "md5": "cbf5eabb5cbaaacbb930b27dc78426ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust.jar",
          "size": 75726,
          "sha512": "41b68a28f66199031ecda3f5c73f310d8c7f2f0fdc59205411468cc1bf5553d6834b342280ce509f319e1a0d004f1be2ddad10d68ea405a8203b858235648d75",
          "sha256": "0b322e56ea6db56d110db79e3edee4c80849fbe05dec8733ed41f3970726c76c",
          "sha1": "d227641c659ba6f5f0d02270344483bc4b80adde",
          "md5": "cbf5eabb5cbaaacbb930b27dc78426ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust-sources.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust-sources.jar",
          "size": 7729,
          "sha512": "026d34ea8a64202108070460329bb2b75cec0331f69eebd6998ff118e275aa4f3c8e63f355f01d60c22782e8b041d4966f0f327aa12aeea4d6ce6ecfe48293ef",
          "sha256": "5656ab7c99049fb601f50a065329711fd992308dc001eb29987501143394ec37",
          "sha1": "c939342b053407a391e3c28b9563a75aff5f7a6c",
          "md5": "be979e8855b04b479b83728e4f167794"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust-javadoc.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
