{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.7.1-dust.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.2.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.2.jar",
          "size": 274216,
          "sha512": "eb356f97fa5c75b434d8c01297fae0ba52115397a08729344ad35313d8f606af1d8ca9693157247457c09f2085c02715396f04ff588bb4cfd8daa9d8158b3266",
          "sha256": "5042e402da2b23955c09ce2e5f485a54dfd35c883abb6d6347416482f6c5da7e",
          "sha1": "977e816d0b1fc98a514c974493a213597ffeea36",
          "md5": "20ef6e17c7472bd1507efb205f5d9945"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.8-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.2.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.2.jar",
          "size": 274216,
          "sha512": "eb356f97fa5c75b434d8c01297fae0ba52115397a08729344ad35313d8f606af1d8ca9693157247457c09f2085c02715396f04ff588bb4cfd8daa9d8158b3266",
          "sha256": "5042e402da2b23955c09ce2e5f485a54dfd35c883abb6d6347416482f6c5da7e",
          "sha1": "977e816d0b1fc98a514c974493a213597ffeea36",
          "md5": "20ef6e17c7472bd1507efb205f5d9945"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.2-sources.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.2-sources.jar",
          "size": 34827,
          "sha512": "f47ea7f8d2d671c88190781d38532a7e37b676d6ef387f0fdde1217667637b28574f147e27cf63494c12ee4c47038eb0e354821e0369d4a1e6e7a9d9c2a57445",
          "sha256": "6dc7a549f91b216f946fa6d1d61848f13807814b552f81419ca35270a09bb7fc",
          "sha1": "41aef666f10f9df41b8e6dd8c8a729f3a4dcdb6e",
          "md5": "014c934fa4a72d95c0b4d1cd17d1647e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.2-javadoc.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
