{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-access-widener",
    "version": "0.6.0-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust.0.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust.0.jar",
          "size": 77848,
          "sha512": "c0150710efa91db005abd6ce6c2c318541b1c880cc0cdb27ad27384df557be1bd1dd847e2ec15b768c8c0f3f659d41adeb4f293df766d9978ad4112d04826a62",
          "sha256": "9b6df31c50b944d0321256887766c8458e6da533900ed6a0c2285a40960a93ab",
          "sha1": "88c1b1fa6375ee7283cf40862ff383a354fec8dd",
          "md5": "386208659afe56410a2383bf83c72bb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust.0.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust.0.jar",
          "size": 77848,
          "sha512": "c0150710efa91db005abd6ce6c2c318541b1c880cc0cdb27ad27384df557be1bd1dd847e2ec15b768c8c0f3f659d41adeb4f293df766d9978ad4112d04826a62",
          "sha256": "9b6df31c50b944d0321256887766c8458e6da533900ed6a0c2285a40960a93ab",
          "sha1": "88c1b1fa6375ee7283cf40862ff383a354fec8dd",
          "md5": "386208659afe56410a2383bf83c72bb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust.0-sources.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust.0-sources.jar",
          "size": 7819,
          "sha512": "3bf55c4263f50ec7a1c08a88cae324fb50634a27453a0625b99fc6aa5e31ca3f0412179b698f4cf5289d0ccd1161417c3758a84f785e4a122b623386fee94150",
          "sha256": "79c059c8acb5949f16949c7d4e9925ca97d2c39fb123f26092d0165e9769137e",
          "sha1": "d1dbdf3231f893b7966b0a2d64db9a092e33145f",
          "md5": "c75a07d6dc6602b70374914ef5cb9c9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.0-dust.0-javadoc.jar",
          "url": "minecraft-codev-access-widener-0.6.0-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
