{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.7.1-dust.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.3.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.3.jar",
          "size": 274144,
          "sha512": "49c0f5bd450e7be60272253b0d66c77bcda1c38c67ada47f774fc78019eed6c11d65fd242e76cfc9fdd0b61bd872f478e9416260ee0a66081eb30316b02b1df7",
          "sha256": "de568dc5393baee00e814b7c1391730bb7988767d37300a3814976d6f27d108a",
          "sha1": "59d322d520ee31f755050da97424b3104ccb96b0",
          "md5": "2414b16187612052af00c2dcdbbaac67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.8-dust"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.3.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.3.jar",
          "size": 274144,
          "sha512": "49c0f5bd450e7be60272253b0d66c77bcda1c38c67ada47f774fc78019eed6c11d65fd242e76cfc9fdd0b61bd872f478e9416260ee0a66081eb30316b02b1df7",
          "sha256": "de568dc5393baee00e814b7c1391730bb7988767d37300a3814976d6f27d108a",
          "sha1": "59d322d520ee31f755050da97424b3104ccb96b0",
          "md5": "2414b16187612052af00c2dcdbbaac67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.3-sources.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.3-sources.jar",
          "size": 34809,
          "sha512": "b75ab929a0bf69248c3ec0592106120876221b646f1a072491967a01c281e70ddb3bec313d51fd868d5325e7da3ce9ba57607d300e554bb5b3232b046d6bb9cf",
          "sha256": "0592122ea55e7b266b1193fa9b17e07a4436f93d11e458e1589fb72b41f3a575",
          "sha1": "f71a577e8c73582a390d7f4ebef0750f622b8b49",
          "md5": "94ab04d1cbfd5e1572effbde4a42b103"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.7.1-dust.3-javadoc.jar",
          "url": "minecraft-codev-forge-0.7.1-dust.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
